### ISSUE TITLE
onUpdate was not trigged when is in scrolling

### ISSUE THREAD

**Issue by zacksleo** [citizen55/Phaser3-KineticScrolling#1]
If I swipe/scroll on ios, onUpdate was not trigged when is in scrolling

**Comment by citizen55** [comment]
Unfortunately, I haven't this device. But on my android device it trigged fine. If you show your code maybe i will help you. Or you can use src/main.js and check line 223 or/and 411 with string "if (typeof this.settings.onUpdate === 'function') "

**Comment by zacksleo** [comment]
Thanks for your response.

 After some research, I found update function can met my need.

```typescript

  private cameraPrevY;

 update() {
    const scrollY = this.cameras.main.scrollY;
    if (this.cameraPrevY !== scrollY) {
      // scroll event
      this.cameraPrevY = scrollY;
    }
  }
